language: clojure
lein: lein
dist: trusty
jdk:
   - oraclejdk8
branches:
  only:
    - master
before_install:
  - cd /tmp
  - wget https://sourceforge.net/projects/gnuplot/files/gnuplot/5.2.6/gnuplot-5.2.6.tar.gz
  - tar -xf gnuplot-5.2.6.tar.gz
  - cd gnuplot-5.2.6
  - ./configure --prefix=$HOME/local
  - make -j2
  - make install
  - export PATH="$HOME/local/bin:$PATH"
  - echo PATH
  - cd
  - gnuplot --version
  - gnuplot -e 'set term'
  - cd jepsen
script: lein do clean, test
notifications:
  email:
    on_success: never
    on_failure: never
