version: '2'
services:
  control:
    container_name: jepsen-control
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    ports:
      - "8080"
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
  node:
    container_name: jepsen-node
    build: ./node
    env_file: ./secret/node.env
    privileged: true
  n1:
    extends: node
    container_name: jepsen-n1
    hostname: n1
  n2:
    extends: node
    container_name: jepsen-n2
    hostname: n2
  n3:
    extends: node
    container_name: jepsen-n3
    hostname: n3
  n4:
    extends: node
    container_name: jepsen-n4
    hostname: n4
  n5:
    extends: node
    container_name: jepsen-n5
    hostname: n5
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
